/**
 * Pre-build script: reads chart.umd.js and exports as a JSON-safe string constant.
 * Run before tsup via npm run prebuild.
 */
const { readFileSync, writeFileSync } = require("fs");

const src = readFileSync("node_modules/chart.js/dist/chart.umd.js", "utf8");
// JSON.stringify handles all escaping correctly
const jsonStr = JSON.stringify(src);

writeFileSync(
  "src/chartjs-inline.ts",
  `/** Auto-generated by scripts/embed-chartjs.cjs — do not edit */\nexport const CHARTJS_SOURCE: string = ${jsonStr};\n`
);

console.log(`Embedded chart.js (${src.length} bytes) into src/chartjs-inline.ts`);
